image: node:8

before_script:
- echo -e "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n" > ~/.npmrc
- yarn
- node -v
- npm -v
- yarn -v
- yarn tsc -v

stages:
- check
- test
- build
- deploy

lint:
  stage: check
  script:
  - yarn lint
  cache:
    key: ${CI_PIPELINE_IID}
    paths:
    - node_modules/
    policy: push

test:
  stage: test
  script:
  - yarn test --coverage --no-cache
  cache:
    key: ${CI_PIPELINE_IID}
    paths:
    - node_modules/
    policy: pull
  coverage: '/All files\s+\|\s+([\d\.]+)/'

build:
  stage: build
  script:
  - yarn build
  - yarn build:docs
  cache:
    key: ${CI_PIPELINE_IID}
    paths:
    - node_modules/
    policy: pull
  artifacts:
    paths:
    - dist/*

deploy tag:
  stage: deploy
  only:
  - tags
  cache:
    key: ${CI_PIPELINE_IID}
    paths:
    - node_modules/
    policy: pull
  script:
  - yarn publish --access public --new-version ${CI_COMMIT_TAG}
